sudo: required
language: node_js
node_js:
- node
notifications:
  email:
    on_success: always # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - midhun@zeefasys.com
      - sabreena@zeefasys.com
cache:
  directories:
    - node_modules
after_success:
- chmod +x deploy.sh
- "./deploy.sh"